### ISSUE TITLE
Unicode characters not supported

### ISSUE THREAD

**Issue by Krettis** [potherca/Parrots#1]
Tried to add some [smilies, umbrellas and musicnotes]( https://jebentzelfeen.herokuapp.com/%E2%9D%A4%20%E2%99%8E%20%E2%98%80%20%E2%98%85%20%E2%98%82%20%E2%99%9E%20%E2%98%AF%20%E2%98%AD%20%E2%98%A2%20%E2%82%AC%20%E2%98%8E%20%E2%9A%91%20%E2%9D%84%20%E2%99%AB%20%E2%9C%82)
But unfortunately...

**Comment by potherca** [comment]
I've pushed some changes that might address this issue.
The link seems to be working (both in Chrome and Firefox on linux). 
could you try again? If it does not work for you, which browser and OS are you using?

**Comment by Krettis** [comment]
Ja doet het nu weer :+1: osx, chrome en firefox getest
