### ISSUE TITLE
Adding plus to the form doesn't show a plus in the text

### ISSUE THREAD

**Issue by Krettis** [potherca/Parrots#2]
Typing in `2+2=5`, this will do the following output: 2 2=5 on the screen.

First problem it is putting the '+' in the url. Second problem is that manual URL-encoding also doesn't help: `2%2B2=5`

**Comment by potherca** [comment]
The `+` *should* not be decoded to a space, only `%2B`. 
Looks like the URL encoding logic needs a closer look.

**Comment by potherca** [comment]
Using the `?subject=` format works but only with `%2B`, not with a plain plus `+`.
I get the feeling this may have something to do with the redirect in the .htaccess as the plus-sign is already stripped before the `index.php` is run.

**Comment by Krettis** [comment]
Sorry I meant typing in 2+2=5 on the form. In that case the `+` already should be encoded. 
[This stackoverflow topic](http://stackoverflow.com/questions/459667/how-to-encode-special-characters-using-mod-rewrite-apache) could be the solution regarding the .htacces

**Comment by potherca** [comment]
Already implemented a fix... about to push a new release now... Hold on :smile_cat:
