### ISSUE TITLE
Javascript shizzle

### ISSUE THREAD

**Issue by kvdleij** [potherca/Parrots#5]
http://jebentzelfeen.herokuapp.com/%3Cscript%20src=%22http://code.jquery.com/jquery-latest.min.js%22type=%22text/javascript%22%3E%3C/script%3E%3Cscript%20type=%22text/javascript%22%3E$%28%27.prefix%27%29.css%28%27color%27,%20%27red%27%29;%3C/script%3E

Look what I found!

**Comment by potherca** [comment]
Looking at the page-source the subject does seem to get encoded but somehow it is not displayed on the page. The following does color the word `foo` red: http://jebentzelfeen.herokuapp.com/%3Cspan%20style=%22color:red;%22%3Efoo%3C/span%3E

So it seems that HTML encoding needs to be verified...

**Comment by kvdleij** [comment]
Definitely, because this can also be done: 
http://jebentzelfeen.herokuapp.com/%3Cspan%20style=%22color:white;cursor:pointer;%22%20onclick=%22alert%28%27hoi%27%29%22%3Efoo%3C/span%3E
